"""Canonical fuel charge category codes (Segment B)."""

from __future__ import annotations

from typing import Final

CATEGORY_FUEL = "FUEL"
CATEGORY_DEF = "DEF"
CATEGORY_SCALE = "SCALE"
CATEGORY_LUMPER = "LUMPER"
CATEGORY_TOLL = "TOLL"
CATEGORY_CASH_ADVANCE = "CASH_ADVANCE"
CATEGORY_PARKING = "PARKING"
CATEGORY_REPAIR_OR_SERVICE = "REPAIR_OR_SERVICE"
CATEGORY_PRODUCT_PURCHASE = "PRODUCT_PURCHASE"
CATEGORY_OTHER = "OTHER"
CATEGORY_UNMAPPED = "UNMAPPED"

# Locked business categories (charge types). UNMAPPED is operational workflow only.
LOCKED_CHARGE_CATEGORY_CODES: Final[frozenset[str]] = frozenset(
    {
        CATEGORY_FUEL,
        CATEGORY_DEF,
        CATEGORY_SCALE,
        CATEGORY_LUMPER,
        CATEGORY_CASH_ADVANCE,
        CATEGORY_PRODUCT_PURCHASE,
        CATEGORY_REPAIR_OR_SERVICE,
        CATEGORY_PARKING,
        CATEGORY_TOLL,
        CATEGORY_OTHER,
    }
)

CANONICAL_CATEGORY_CODES: Final[frozenset[str]] = LOCKED_CHARGE_CATEGORY_CODES | {CATEGORY_UNMAPPED}

CATEGORY_SEED_ROWS: Final[tuple[tuple[str, str, str], ...]] = (
    (CATEGORY_FUEL, "Fuel", "Fuel purchases (e.g. diesel/gas)"),
    (CATEGORY_DEF, "DEF", "Diesel exhaust fluid"),
    (CATEGORY_SCALE, "Scale", "Scale/weigh charges"),
    (CATEGORY_LUMPER, "Lumper", "Lumper / unloading labor"),
    (CATEGORY_TOLL, "Toll", "Toll charges"),
    (CATEGORY_CASH_ADVANCE, "Cash advance", "Cash advance"),
    (CATEGORY_PARKING, "Parking", "Parking"),
    (CATEGORY_REPAIR_OR_SERVICE, "Repair or service", "Repair or service"),
    (CATEGORY_PRODUCT_PURCHASE, "Product purchase", "Other product purchase"),
    (CATEGORY_OTHER, "Other", "Other charge"),
    (CATEGORY_UNMAPPED, "Unmapped", "Not yet classified"),
)

CLASSIFICATION_STATUS_CONFIRMED = "CONFIRMED"
CLASSIFICATION_STATUS_UNMAPPED = "UNMAPPED"

CLASSIFICATION_SOURCE_PROVIDER_RULE = "PROVIDER_RULE"
CLASSIFICATION_SOURCE_SYSTEM_MAPPING = "SYSTEM_MAPPING"
CLASSIFICATION_SOURCE_TENANT_MAPPING = "TENANT_MAPPING"
CLASSIFICATION_SOURCE_MANUAL = "MANUAL"

MAPPING_SOURCE_PROVIDER_RULE = "PROVIDER_RULE"
MAPPING_SOURCE_SYSTEM_MAPPING = "SYSTEM_MAPPING"
MAPPING_SOURCE_TENANT_MAPPING = "TENANT_MAPPING"
MAPPING_SOURCE_MANUAL = "MANUAL"

CLASSIFICATION_SOURCES: Final[frozenset[str]] = frozenset(
    {
        CLASSIFICATION_SOURCE_PROVIDER_RULE,
        CLASSIFICATION_SOURCE_SYSTEM_MAPPING,
        CLASSIFICATION_SOURCE_TENANT_MAPPING,
        CLASSIFICATION_SOURCE_MANUAL,
    }
)
