#!/usr/bin/env bash
set -euo pipefail

PG_CONTAINER="trucking_erp-truckerp-postgres-1"
OUT_DIR="/home/admin/trucking_erp/docs/db_schema"
DBS=("trucking_erp" "tenant_smoke_active" "tenant_smoke_provision")

mkdir -p "$OUT_DIR"

psqlc () {
  local db="$1"; shift
  docker exec -i "$PG_CONTAINER" psql -U postgres -d "$db" -v ON_ERROR_STOP=1 -qAt -c "$*"
}

ts_utc="$(date -u +"%Y-%m-%d %H:%M:%SZ")"

# README
cat > "$OUT_DIR/README.md" <<MD
# Database Schema Docs

Generated by: \`export_schema_docs_v2.sh\`
Time (UTC): \`$ts_utc\`

Databases documented:
- trucking_erp (platform)
- tenant_smoke_active (tenant)
- tenant_smoke_provision (tenant)

Each schema file includes:
- Tables
- Primary keys
- Foreign keys (outbound)
- Referenced By (inbound / reverse foreign keys)
- Column details (type, nullable, default)
MD

for db in "${DBS[@]}"; do
  out="$OUT_DIR/${db}__schema.md"

  {
    echo "# Schema: ${db}"
    echo
    echo "- Generated (UTC): \`$ts_utc\`"
    echo "- Postgres container: \`$PG_CONTAINER\`"
    echo

    tables="$(psqlc "$db" "select tablename from pg_tables where schemaname='public' order by tablename;")"

    if [[ -z "${tables// }" ]]; then
      echo "_No tables found in public schema._"
      echo
      continue
    fi

    while IFS= read -r t; do
      [[ -z "${t// }" ]] && continue

      echo "## ${t}"
      echo

      echo "### Columns"
      echo
      echo "| Column | Type | Nullable | Default |"
      echo "|---|---|---:|---|"

      # Column list
      psqlc "$db" "
        select
          c.column_name,
          case
            when c.data_type='USER-DEFINED' then c.udt_name
            else c.data_type
          end as data_type,
          c.is_nullable,
          coalesce(c.column_default,'')
        from information_schema.columns c
        where c.table_schema='public' and c.table_name='${t}'
        order by c.ordinal_position;
      " | while IFS='|' read -r col typ nul def; do
        # basic escaping for markdown pipes
        col="${col//|/\\|}"
        typ="${typ//|/\\|}"
        def="${def//|/\\|}"
        echo "| \`${col}\` | \`${typ}\` | ${nul} | \`${def}\` |"
      done

      echo

      echo "### Primary Key"
      echo
      pk="$(psqlc "$db" "
        select string_agg(a.attname, ', ' order by a.attnum)
        from pg_index i
        join pg_class c on c.oid = i.indrelid
        join pg_namespace n on n.oid = c.relnamespace
        join pg_attribute a on a.attrelid = c.oid and a.attnum = any(i.indkey)
        where n.nspname='public' and c.relname='${t}' and i.indisprimary;
      ")"
      if [[ -n "${pk// }" ]]; then
        echo "- \`${pk}\`"
      else
        echo "_None_"
      fi
      echo

      echo "### Foreign Keys (Outbound)"
      echo
      fks_out="$(psqlc "$db" "
        select
          kcu.column_name || ' -> ' || ccu.table_name || '.' || ccu.column_name
        from information_schema.table_constraints tc
        join information_schema.key_column_usage kcu
          on tc.constraint_name = kcu.constraint_name
         and tc.table_schema = kcu.table_schema
        join information_schema.constraint_column_usage ccu
          on ccu.constraint_name = tc.constraint_name
         and ccu.table_schema = tc.table_schema
        where tc.constraint_type='FOREIGN KEY'
          and tc.table_schema='public'
          and tc.table_name='${t}'
        order by 1;
      ")"
      if [[ -n "${fks_out// }" ]]; then
        while IFS= read -r line; do
          [[ -z "${line// }" ]] && continue
          echo "- \`${line}\`"
        done <<< "$fks_out"
      else
        echo "_None_"
      fi
      echo

      echo "### Referenced By"
      echo
      # Inbound / reverse FK: who references this table
      fks_in="$(psqlc "$db" "
        select
          tc.table_name || '.' || kcu.column_name || ' -> ${t}.' || ccu.column_name
        from information_schema.table_constraints tc
        join information_schema.key_column_usage kcu
          on tc.constraint_name = kcu.constraint_name
         and tc.table_schema = kcu.table_schema
        join information_schema.constraint_column_usage ccu
          on ccu.constraint_name = tc.constraint_name
         and ccu.table_schema = tc.table_schema
        where tc.constraint_type='FOREIGN KEY'
          and tc.table_schema='public'
          and ccu.table_schema='public'
          and ccu.table_name='${t}'
        order by 1;
      ")"
      if [[ -n "${fks_in// }" ]]; then
        while IFS= read -r line; do
          [[ -z "${line// }" ]] && continue
          echo "- \`${line}\`"
        done <<< "$fks_in"
      else
        echo "_None_"
      fi
      echo
    done <<< "$tables"

  } > "$out"

  echo "✅ wrote $out"
done

echo "✅ Done. Output in: $OUT_DIR"
