"""driver phones constraints and indexes

Revision ID: 476789399da2
Revises: a59de96e634e
Create Date: 2025-12-24 04:20:46.546491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476789399da2'
down_revision: Union[str, Sequence[str], None] = 'a59de96e634e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('phone_type', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'country_code', 'phone_number', name='uq_driver_phone_dedupe')
    )
    op.create_index('ix_driver_phones_driver_id', 'driver_phones', ['driver_id'], unique=False)
    op.create_index('ix_driver_phones_phone_number', 'driver_phones', ['phone_number'], unique=False)
    op.create_index('ux_driver_primary_phone', 'driver_phones', ['driver_id'], unique=True, postgresql_where=sa.text('is_primary'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_driver_primary_phone', table_name='driver_phones', postgresql_where=sa.text('is_primary'))
    op.drop_index('ix_driver_phones_phone_number', table_name='driver_phones')
    op.drop_index('ix_driver_phones_driver_id', table_name='driver_phones')
    op.drop_table('driver_phones')
    # ### end Alembic commands ###
